### ISSUE TITLE
Exceptions are thrown when a request is made

### ISSUE THREAD

**Issue by dvberkel** [ClojureNauts/clojurenauts-twitter-bot#1]
When running `lein repl` and starting a server as demonstrated below

``` shell
> lein repl
nREPL server started on port 52844 on host 127.0.0.1 - nrepl://127.0.0.1:52844
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_20-b26
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

bot.core=> (require 'bot.web)
nil
bot.core=> (def server (bot.web/-main))
2015-04-17 14:06:30.372:INFO:oejs.Server:jetty-7.6.8.v20121106
2015-04-17 14:06:30.409:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:5000
#'bot.core/server
```

Given that I visit the `http://localhost:5000` the following exception is logged in the repl

```
2015-04-17 14:06:43.882:WARN:oejs.AbstractHttpConnection:/favicon.ico
java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
    at clojure.java.io$fn__8628$G__8610__8635.invoke(io.clj:69)
    at clojure.java.io$reader.doInvoke(io.clj:102)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$slurp.doInvoke(core.clj:6390)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at bot.web$fn__5122.invoke(web.clj:18)
    at compojure.core$make_route$fn__3876.invoke(core.clj:99)
    at compojure.core$if_route$fn__3860.invoke(core.clj:45)
    at compojure.core$if_method$fn__3853.invoke(core.clj:30)
    at compojure.core$routing$fn__3882.invoke(core.clj:112)
    at clojure.core$some.invoke(core.clj:2515)
    at compojure.core$routing.doInvoke(core.clj:112)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:626)
    at compojure.core$routes$fn__3886.invoke(core.clj:117)
    at clojure.lang.Var.invoke(Var.java:379)
    at ring.middleware.keyword_params$wrap_keyword_params$fn__4136.invoke(keyword_params.clj:32)
    at ring.middleware.nested_params$wrap_nested_params$fn__4185.invoke(nested_params.clj:75)
    at ring.middleware.params$wrap_params$fn__4102.invoke(params.clj:58)
    at ring.middleware.multipart_params$wrap_multipart_params$fn__4229.invoke(multipart_params.clj:107)
    at ring.middleware.flash$wrap_flash$fn__4862.invoke(flash.clj:31)
    at ring.middleware.session$wrap_session$fn__4842.invoke(session.clj:85)
    at ring.adapter.jetty$proxy_handler$fn__5058.invoke(jetty.clj:18)
    at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:363)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:920)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:982)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dvberkel** [comment]
Since commit 613818d06f3c69e2a13f35e29ffe5f0e9e976201 you need to `(require 'bot.core)`.

**Comment by dvberkel** [comment]
The exception is not thrown when the server is reached with the following command

``` sh
curl -X GET http://localhost:5000
```

**Comment by dvberkel** [comment]
The exception is triggered when requesting any other other route and is throw by the following [code](https://github.com/ClojureNauts/clojurenauts-twitter-bot/blob/5787c991b73e2ad7d6a564c8fd96f76772480bfd/src/bot/web.clj#L15)

**Comment by dvberkel** [comment]
This seems to be the following [known issue](http://dev.clojure.org/jira/browse/CLJ-1210).

The root cause would be that it can not find the `404.html`.

**Comment by pxlpnk** [comment]
oh I somehow didn't follow your progress here! nice work!

**Comment by dvberkel** [comment]
@pxlpnk sorry, I need to figure out IRC a bit so that I can more easily communicate.

But I have the intention to write up my experiences on creating the bot once it works properly.

**Comment by pxlpnk** [comment]
No worries! We can also drop IRC and use gitter or something like this!
I don't really mind (:

Daan van Berkel notifications@github.com writes:

> @pxlpnk sorry, I need to figure out IRC a bit so that I can more easily communicate.
> 
> But I have the intention to write up my experiences on creating the bot once it works properly.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClojureNauts/clojurenauts-twitter-bot/issues/1#issuecomment-95099327

## 

Andreas Tiefenthaler -- http://an-ti.eu

**Comment by dvberkel** [comment]
I actually want to figure out IRC, but I guess Gitter is easier to figure out. Let's do both

**Comment by pxlpnk** [comment]
uh both? halp so much overcommunication :D
